# Generated by Django 5.2.6 on 2025-09-06 11:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key_prefix', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_emails', models.IntegerField(default=0)),
                ('urgent_emails', models.IntegerField(default=0)),
                ('responded_emails', models.IntegerField(default=0)),
                ('pending_emails', models.IntegerField(default=0)),
                ('positive_emails', models.IntegerField(default=0)),
                ('negative_emails', models.IntegerField(default=0)),
                ('neutral_emails', models.IntegerField(default=0)),
                ('technical_issues', models.IntegerField(default=0)),
                ('account_support', models.IntegerField(default=0)),
                ('product_inquiries', models.IntegerField(default=0)),
                ('billing_issues', models.IntegerField(default=0)),
                ('general_inquiries', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('received_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=10, null=True)),
                ('sentiment_confidence', models.FloatField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('normal', 'Normal')], default='normal', max_length=10)),
                ('category', models.CharField(blank=True, choices=[('technical_issue', 'Technical Issue'), ('account_support', 'Account Support'), ('product_inquiry', 'Product Inquiry'), ('billing', 'Billing'), ('general', 'General')], max_length=20, null=True)),
                ('extracted_info', models.JSONField(blank=True, default=dict)),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('response_generated_at', models.DateTimeField(blank=True, null=True)),
                ('is_responded', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_urgent', '-received_at'],
                'indexes': [models.Index(fields=['received_at'], name='emailbot_em_receive_f8c9fb_idx'), models.Index(fields=['priority'], name='emailbot_em_priorit_31ab06_idx'), models.Index(fields=['sentiment'], name='emailbot_em_sentime_2c1e47_idx'), models.Index(fields=['is_urgent'], name='emailbot_em_is_urge_9ce1d8_idx')],
            },
        ),
    ]
